### ISSUE TITLE
Add the name of the invoking user to the message

### ISSUE THREAD

**Issue by freyjasdottir** [freyjasdottir/chowdabot#1]
I would like the bot to include the name of the user who invoked it in the message output.

**Comment by freyjasdottir** [comment]
I have this working and tested on dev as well.  The incoming params hash contains the user name of the user that invoked the bot. So I passed that on to `adminize_message` and added some text to the outgoing message.

**Comment by freyjasdottir** [comment]
Could use a code review.

**Comment by hypatian** [comment]
This was fixed in 4aa0cc02f746323dc21443cfcfe91ab5c01451ba. I have added a comment to that commit.
