### ISSUE TITLE
Mentions sent in the slash command do not become mentions in the outgoing message

### ISSUE THREAD

**Issue by hypatian** [freyjasdottir/chowdabot#2]
After passing through the bot, mentions of `@username` don't become mentions. Channel mentions probably work the same way. It might be good to make channel and user references become mentions.

**Comment by freyjasdottir** [comment]
Fixed on dev. I added `"link_names": 1` to the JSON response that Chowdabot sends to Slack.

**Comment by freyjasdottir** [comment]
Tested and fixed on prod.
