### ISSUE TITLE
Refactor adminize_message and how messages are sent to the webhook

### ISSUE THREAD

**Issue by freyjasdottir** [freyjasdottir/chowdabot#3]
The number of parameters I'm passing to `adminize_message` is starting to get unwieldy, and I can see this list growing.

I'd like to do two things to remedy this and make my life easier later:
1) Collect the parameters I'm passing to `adminize_message` into a hash instead of passing each individually, then pass that hash.

2) Separate out into two functions the load of message creation and message sending. This might make my life easier later for multiple message support.

**Comment by freyjasdottir** [comment]
I decided I wanted both adminize and post in a SlackMessenger class, since they way they work is specifically for sending messages to Slack.

**Comment by freyjasdottir** [comment]
Ready for a code review when you're ready @hypatian

**Comment by hypatian** [comment]
Looks good to me. It accounts for all the cases that currently exist. :)
